# General tmux settings
source-file ~/.tmux/general.conf

# Keybindings
source-file ~/.tmux/key-bindings.conf

# Colors
source-file ~/.tmux/colors/tokyonight.conf

# Visual styling
source-file ~/.tmux/styles/pill.conf

