# ============================================
# Status bar
# ============================================

set -g status-style "bg=#{@status_bar_bg},fg=#{@inactive_text_color}"

set -g status-left " "

# Right status: [ host ]
set -g status-right "\
#[fg=#{@text_primary},bg=#{@surface_bg}][\
#[fg=#{@text_primary},bg=#{@surface_bg}]#H\
#[fg=#{@text_primary},bg=#{@surface_bg}]]\
"

set -g status-right-length 100


# ============================================
# Current window
# ============================================

# [ 1:window_name ]
set -g window-status-current-format "\
#[fg=#{@accent_primary},bg=#{@surface_bg}][\
#[fg=#{@accent_primary},bg=#{@surface_bg},bold]#I:#W\
#[fg=#{@accent_primary},bg=#{@surface_bg},nobold]]\
"


# ============================================
# Inactive windows
# ============================================

# [ 1:window_name ]
set -g window-status-format "\
#[fg=#{@text_primary},bg=#{@surface_bg}][\
#[fg=#{@text_primary},bg=#{@surface_bg}]#I:#W\
#[fg=#{@text_primary},bg=#{@surface_bg}]]\
"


# ============================================
# Pane borders
# ============================================

set -g pane-border-style "fg=#{@accent_secondary}"
set -g pane-active-border-style "fg=#{@accent_primary}"

