HALF_ROUND_OPEN=""
HALF_ROUND_CLOSE=""


# ============================================
# Status bar
# ============================================

set -g status-style "bg=#{@surface_bg},fg=#{@text_primary}"

set -g status-left " "

set -g status-right "\
#[fg=#{@accent_secondary},bg=#{@surface_bg}]${HALF_ROUND_OPEN}\
#[fg=default,bg=#{@accent_secondary}]#H\
#[fg=#{@accent_secondary},bg=#{@surface_bg}]${HALF_ROUND_CLOSE}\
"

set -g status-right-length 100


# ============================================
# Current window
# ============================================

set -g window-status-current-format "\
#[fg=#{@accent_primary},bg=#{@surface_bg}]${HALF_ROUND_OPEN}\
#[fg=#{@text_secondary},bg=#{@accent_primary},bold]#I:#W\
#[fg=#{@accent_primary},bg=#{@surface_bg},nobold]${HALF_ROUND_CLOSE}\
"


# ============================================
# Inactive windows
# ============================================

set -g window-status-format "\
#[fg=#{@accent_secondary},bg=#{@surface_bg}]${HALF_ROUND_OPEN}\
#[fg=default,bg=#{@accent_secondary}]#I:#W\
#[fg=#{@accent_secondary},bg=#{@surface_bg}]${HALF_ROUND_CLOSE}\
"


# ============================================
# Pane borders
# ============================================

set -g pane-border-style "fg=#{@accent_secondary}"
set -g pane-active-border-style "fg=#{@accent_primary}"
