HALF_ROUND_OPEN=""
HALF_ROUND_CLOSE=""


# ============================================
# Status bar
# ============================================

set -g status-style "bg=#{@status_bar_bg},fg=#{@inactive_text_color}"

set -g status-left " "

set -g status-right "\
#[fg=#{@inactive_bg_color},bg=#{@status_bar_bg}]${HALF_ROUND_OPEN}\
#[fg=default,bg=#{@inactive_bg_color}]#H\
#[fg=#{@inactive_bg_color},bg=#{@status_bar_bg}]${HALF_ROUND_CLOSE}\
"

set -g status-right-length 100


# ============================================
# Current window
# ============================================

set -g window-status-current-format "\
#[fg=#{@active_bg_color},bg=#{@status_bar_bg}]${HALF_ROUND_OPEN}\
#[fg=#{@active_text_color},bg=#{@active_bg_color},bold]#I:#W\
#[fg=#{@active_bg_color},bg=#{@status_bar_bg},nobold]${HALF_ROUND_CLOSE}\
"


# ============================================
# Inactive windows
# ============================================

set -g window-status-format "\
#[fg=#{@inactive_bg_color},bg=#{@status_bar_bg}]${HALF_ROUND_OPEN}\
#[fg=default,bg=#{@inactive_bg_color}]#I:#W\
#[fg=#{@inactive_bg_color},bg=#{@status_bar_bg}]${HALF_ROUND_CLOSE}\
"


# ============================================
# Pane borders
# ============================================

set -g pane-border-style "fg=#{@inactive_bg_color}"
set -g pane-active-border-style "fg=#{@active_bg_color}"
