# Set Ctrl-s as Prefix
set -g prefix C-s

# Make sure oh-my-zsh color themes work correctly
set -g default-terminal "screen-256color"

# For better navigation
setw -g mode-keys vi

# Increase scrollback buffer size
set -g history-limit 10000

# Use system clipboard
# set-option -g set-clipboard on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on
